### PR TITLE
added _.has

### PR DESCRIPTION
**Pull request by OliverRadini**

### CODE REVIEW

**Comment by chroventer** [comment]
Does the native implementation support path functionality?

```js
_.has(object, 'a.b.c');
// => true
```

**Comment by OliverRadini** [comment]
@chroventer It does; sorry, I missed that. I was looking at the implementation [here](https://github.com/lodash/lodash/blob/master/has.js) which doesn't seem to support `path` at all (I'm guessing it's supported elsewhere). I'll look into that and see what I can find

**Comment by chroventer** [comment]
> @chroventer It does; sorry, I missed that. I was looking at the implementation [here](https://github.com/lodash/lodash/blob/master/has.js) which doesn't seem to support `path` at all (I'm guessing it's supported elsewhere). I'll look into that and see what I can find

Fine by me, thanks for the fast response. I had linked the newest version of [_.has](https://lodash.com/docs/4.17.15#has) in the issue for citing as well 😅

**Comment by cht8687** [comment]
@you-dont-need/lodash-underscore  
any thoughts about the `path`?

**Comment by OliverRadini** [comment]
I'd forgotten about this; I'll take a look at getting this resolved

**Comment by OliverRadini** [comment]
@cht8687 @chroventer  This should hopefully be updated to handle paths now; hope that covers it

**Pull request merged**
