### PR TITLE
Adding native _.uniq method replacement

### PR DESCRIPTION
**Pull request by adyngom**
This technique takes advantage of the new Set construct introduced in ES6 to ensure that no duplicates
are present in the resulting array.

### CODE REVIEW

**Comment by stevemao** [comment]
@adyngom Could you resolve the conflicts?

**Comment by adyngom** [comment]
@stevemao hmmm i'm not sure what is failing since there is no conflict, looking at the Travis log it seems to be an nvm related issue. Not sure if it's related but when I do
```nvm list```
this is what I get on my local
```sh
adyngom@Adys-MBP:~/Code/You-Dont-Need-Lodash-Underscore$ nvm list
->       v5.0.0
         v5.1.0
         v8.1.3
         system
default -> 5.0 (-> v5.0.0)
node -> stable (-> v8.1.3) (default)
stable -> 8.1 (-> v8.1.3) (default)
iojs -> N/A (default)
lts/* -> lts/boron (-> N/A)
lts/argon -> v4.8.4 (-> N/A)
lts/boron -> v6.11.4 (-> N/A)
```

**Comment by cht8687** [comment]
This will fix it. https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore/pull/105/commits/3c9c5bce9837857cc14f2a3c6f84367f79443d35

**Comment by adyngom** [comment]
Nice @cht8687 - thanks

**Pull request merged**
