### PR TITLE
Append flatten and flattenDeep

### PR DESCRIPTION
**Pull request by inuscript**
Append altanative function for `flatten` and `flattenDeep`

### CODE REVIEW

**Comment by stevemao** [comment]
Almost anything could be done with `reduce()`, any with es6+ its relatively easy. I'm not sure how far we should go

**Comment by cht8687** [comment]
This merge request provides alternatives for `_flatten` and `_flattendeep`, it provides useful information for users to take the advantage of `reduce` function. What do you think? @stevemao

**Comment by cht8687** [comment]
We can squash the commits though if we'd merge it.

**Comment by stevemao** [comment]
I don't have any strong opinion on this.

**Comment by inuscript** [comment]
I squashed commits.

**Comment by cht8687** [comment]
👍

**Pull request merged**
