### PR TITLE
Minor fix to _.intersection alternative implementation

### PR DESCRIPTION
**Pull request by arunrreddy**

### CODE REVIEW

**Comment by cjtaylor1990** [comment]
Good job catching this typo!

**Comment by cht8687** [comment]
@cjtaylor1990  
I just checked the rules and tests, it seems `arrays` are rarely declared. should be all good.

**Comment by cjtaylor1990** [comment]
@cht8687 Great. I would have checked myself but it was very late in my time zone.

**Comment by cht8687** [comment]
thank you @arunrreddy

**Pull request merged**
