### PR TITLE
use camelCase

### PR DESCRIPTION
**Pull request by cht8687**
fix for #65

### CODE REVIEW

**Comment by stevemao** [comment]
The rule names, by convention, should be dash-cased. We should write a special use-case for `is-nan`.

**Comment by stevemao** [comment]
See http://eslint.org/docs/rules/ or other eslint addons.

**Comment by noderat** [comment]
@stevemao presented a convincing argument, this should probably be reverted to follow ESLint rule naming convention

**Comment by stevemao** [comment]
I did, and also fixed `is-nan` bug

**Comment by cht8687** [comment]
@stevemao thank you steve.

**Pull request merged**
