### PR TITLE
include slice as substitute for _initial

### PR DESCRIPTION
**Pull request by icncsx**
@stevemao this is for #258

### CODE REVIEW

**Comment by cht8687** [comment]
@icncsx 
thanks. could you resolve the conflicts so that we can merge this PR?

**Comment by cht8687** [comment]
could you help resolve the conflicts? @icncsx  👍

**Comment by icncsx** [comment]
@cht8687 Conflict resolved. Thanks for reviewing.

**Comment by cht8687** [comment]
👍

**Comment by icncsx** [comment]
Closes #258

**Pull request merged**
