### PR TITLE
Fix get throws error

### PR DESCRIPTION
**Pull request by bmpGames**
Fix issue #204 
1) default value must be undefined, not null
2) Object.hasOwnProperty throws an exception, when it gets null or undefined
3) assert.equal think that null = undefined, changed to strictEqual
4) add some tests

### CODE REVIEW

**Comment by stevemao** [comment]
@clujin looks good to you?

**Comment by bmpGames** [comment]
By the way, this code example is also ES6(const, arrow func, etc)
What do you think?
1) nevermind
2) add es6 mention in readme
3) change the code to es5

**Comment by stevemao** [comment]
I don't think we should care about es6 or not, but browser support for such a snippet.

**Comment by stevemao** [comment]
Thanks!

**Comment by cht8687** [comment]
nice work 👍

**Pull request merged**
