### PR TITLE
Add _.takeRight

### PR DESCRIPTION
**Pull request by ovidiubute**

### CODE REVIEW

**Comment by ovidiubute** [comment]
To all maintainers: is it really worth having [this assertion](https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore/pull/188/files#diff-61c3eeede68f171c613832fc1c735d07R7). I understand the reasoning for it, but if there are at least two PRs opened at the same time that add new rules, it's guaranteed to cause git conflicts. Would you be open to addressing that?

**Comment by cht8687** [comment]
> To all maintainers: is it really worth having [this assertion](https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore/pull/188/files#diff-61c3eeede68f171c613832fc1c735d07R7)?
> 
> I understand the reasoning for it, but if there are at least two PRs opened at the same time that add new rules, it's guaranteed to cause git conflicts. Would you be open to addressing that?

thoughts on this? @stevemao @ovidiubute @shineli1984 ?

**Comment by stevemao** [comment]
@ovidiubute please fix the test and we'll merge this :)

**Comment by cht8687** [comment]
> Looks good. Thanks.

what about the suggestions on the assertion test?

**Comment by ovidiubute** [comment]
Ready for review.

**Pull request merged**
