### PR TITLE
Fix browser support block's indent

### PR DESCRIPTION
**Pull request by inuscript**
I think "Browser support" seems is child element of each functions.

### CODE REVIEW

**Comment by stevemao** [comment]
@cht8687 Can we give @inuscript the write access to the repo since he has contributed a lot? I have created a `lodash-underscore` team in the org.

**Comment by cht8687** [comment]
@stevemao sure. Welcome @inuscript sir!

**Comment by inuscript** [comment]
Wow, surprised !

**Comment by stevemao** [comment]
Welcome onboard :)

**Pull request merged**
