### PR TITLE
improvements to Array chunk method

### PR DESCRIPTION
**Pull request by HugeLetters**
Native chunk method provided in the example is rather slow - these are some simple improvements to it in case people copy code from this repo.

I've tried to keep the formatting consistent with what I saw but apologies if some of it is not.

### CODE REVIEW

**Comment by kungfooman** [comment]
Pretty sure that a simple `for`-loop beats any `reduce`'ing too:

```js
const chunk = (input, size) => {
  const arr = [];
  for (let i = 0; i < input.length; i += size) {
    arr.push(input.slice(i, i + size));
  }
  return arr;
};
const ret = chunk(['a', 'b', 'c', 'd', 'e', 'f'], 3);
console.log(JSON.stringify(ret, null, 2))
```

But I have no interest in testing performance, since it's not a priority for me right now.

**Comment by HugeLetters** [comment]
> Pretty sure that a simple `for`-loop beats any `reduce`'ing too:
> 
> ```js
> const chunk = (input, size) => {
>   const arr = [];
>   for (let i = 0; i < input.length; i += size) {
>     arr.push(input.slice(i, i + size));
>   }
>   return arr;
> };
> const ret = chunk(['a', 'b', 'c', 'd', 'e', 'f'], 3);
> console.log(JSON.stringify(ret, null, 2))
> ```
> 
> But I have no interest in testing performance, since it's not a priority for me right now.

This is definitely even faster but I don't if the purpose of the examples is to be easily accessibly to beginner devs so I've tried to keep modifications to a minimum. I think your example should be included instead of mine but I would like to hear what other people think.

**Comment by ODudek** [comment]
I've created simple [performance test](https://www.measurethat.net/Benchmarks/Show/25899/0/chunk---lodash-vs-javascript-vs-for-loop-vs-reduce)

**Comment by kungfooman** [comment]
> I've created simple [performance test](https://www.measurethat.net/Benchmarks/Show/25899/0/chunk---lodash-vs-javascript-vs-for-loop-vs-reduce)

Nice, interesting, seems like `reduce` is way faster than the `for`-loop:

image

Even though I see potential to optimize it further, like `const n = input.length;` while preallocating the proper `Array` length (instead of using push, just simple `arr[i] = ...`)

**Comment by HugeLetters** [comment]
> I've created simple [performance test](https://www.measurethat.net/Benchmarks/Show/25899/0/chunk---lodash-vs-javascript-vs-for-loop-vs-reduce)

Pretty sure something is wrong with this tool - there's no way lodash method is that much slower than the rest, especially considering it's vastly faster on my PC. 

I get that how I sound when I say I don't believe these benchmarks but I do really find it unlikely that the previous native version which does multiple array copies for every iteration is faster than mine which only does mutations or @kungfooman which does only length/chunkSize array copies.

**Comment by kungfooman** [comment]
> Pretty sure something is wrong with this tool

Lol, had the same feeling... tried to edit the benchmark, but couldn't even find a way to do that, so I forgot about it, bad UI and I'm gone :sweat_smile:

**Comment by HugeLetters** [comment]
This is what I get running locally
```javascript
const chunkNew = (input, size) => {
  return input.reduce((arr, item, idx) => {
    if (idx % size === 0) arr.push([item])
    else arr[arr.length - 1].push(item)

    return arr
  }, [])
}

const chunkOld = (input, size) => {
  return input.reduce((arr, item, idx) => {
    return idx % size === 0 ? [...arr, [item]] : [...arr.slice(0, -1), [...arr.slice(-1)[0], item]]
  }, [])
}

const chunkFor = (input, size) => {
  const arr = []
  for (let i = 0; i < input.length; i += size) arr.push(input.slice(i, i + size))

  return arr
}

for (const _ of Array(100)) {
  //   warmup
  const testArray = new Array(10000).fill(1).map(Math.random)

  const nativeOld = chunkOld(testArray, 37)
  const nativeNew = chunkNew(testArray, 37)
  const nativeFor = chunkFor(testArray, 37)
}

const arraySizes = [10, 10_000, 1_000_000]
const chunkSizes = [2, 10, 100, 12345]

for (const arraySize of arraySizes) {
  const testArray = new Array(arraySize).fill(1).map(Math.random)
  for (const chunkSize of chunkSizes) {
    if (chunkSize > arraySize) continue

    console.time(`native old - ${arraySize} by ${chunkSize}`)
    const nativeOld = chunkOld(testArray, chunkSize)
    console.timeEnd(`native old - ${arraySize} by ${chunkSize}`)

    console.time(`native new - ${arraySize} by ${chunkSize}`)
    const nativeNew = chunkNew(testArray, chunkSize)
    console.timeEnd(`native new - ${arraySize} by ${chunkSize}`)

    console.time(`native for - ${arraySize} by ${chunkSize}`)
    const nativeFor = chunkFor(testArray, chunkSize)
    console.timeEnd(`native for - ${arraySize} by ${chunkSize}`)
  }
}
```

And results are 
```
native old - 10 by 2: 0.214ms
native new - 10 by 2: 0.023ms
native for - 10 by 2: 0.02ms
native old - 10 by 10: 0.03ms
native new - 10 by 10: 0.022ms
native for - 10 by 10: 0.017ms
native old - 10000 by 2: 141.427ms
native new - 10000 by 2: 1.006ms
native for - 10000 by 2: 0.329ms
native old - 10000 by 10: 40.339ms
native new - 10000 by 10: 0.639ms
native for - 10000 by 10: 0.329ms
native old - 10000 by 100: 12.191ms
native new - 10000 by 100: 0.342ms
native for - 10000 by 100: 0.034ms
```
It just gets stuck because old is so slow. If a remove it I get
```
native new - 10 by 2: 0.169ms
native for - 10 by 2: 0.019ms
native new - 10 by 10: 0.023ms
native for - 10 by 10: 0.013ms
native new - 10000 by 2: 0.827ms
native for - 10000 by 2: 0.364ms
native new - 10000 by 10: 0.497ms
native for - 10000 by 10: 0.077ms
native new - 10000 by 100: 0.62ms
native for - 10000 by 100: 0.05ms
native new - 1000000 by 2: 303.994ms
native for - 1000000 by 2: 180.829ms
native new - 1000000 by 10: 54.919ms
native for - 1000000 by 10: 23.671ms
native new - 1000000 by 100: 64.11ms
native for - 1000000 by 100: 8.268ms
native new - 1000000 by 12345: 57.577ms
native for - 1000000 by 12345: 6.329ms
```

**Comment by HugeLetters** [comment]
> > Pretty sure something is wrong with this tool
> 
> Lol, had the same feeling... tried to edit the benchmark, but couldn't even find a way to do that, so I forgot about it, bad UI and I'm gone 😅

I've tried the other online [benchmarking tool](https://perf.link/#eyJpZCI6InFkcGJ2bWx4Z2xsIiwidGl0bGUiOiJGaW5kaW5nIG51bWJlcnMgaW4gYW4gYXJyYXkgb2YgMTAwMCIsImJlZm9yZSI6ImNvbnN0IHZhbHVlcyA9IG5ldyBBcnJheSgyMDAgKiAyMDAgKiA0KVxuY29uc3QgY2h1bmtOZXcgPSAoaW5wdXQsIHNpemUpID0%2BIHtcbiAgcmV0dXJuIGlucHV0LnJlZHVjZSgoYXJyLCBpdGVtLCBpZHgpID0%2BIHtcbiAgICBpZiAoaWR4ICUgc2l6ZSA9PT0gMCkge1xuICAgICAgYXJyLnB1c2goW2l0ZW1dKTtcbiAgICB9XG4gICAgZWxzZSB7XG4gICAgICBhcnJbYXJyLmxlbmd0aCAtIDFdLnB1c2goaXRlbSk7XG4gICAgfVxuXG4gICAgcmV0dXJuIGFycjtcbiAgfSwgW10pO1xufVxuXG5jb25zdCBjaHVua09sZCA9IChpbnB1dCwgc2l6ZSkgPT4ge1xuICByZXR1cm4gaW5wdXQucmVkdWNlKChhcnIsIGl0ZW0sIGlkeCkgPT4ge1xuICAgIHJldHVybiBpZHggJSBzaXplID09PSAwXG4gICAgICA%2FIFsuLi5hcnIsIFtpdGVtXV1cbiAgICA6IFsuLi5hcnIuc2xpY2UoMCwgLTEpLCBbLi4uYXJyLnNsaWNlKC0xKVswXSwgaXRlbV1dO1xuICB9LCBbXSk7XG59XG5cbmNvbnN0IGNodW5rRm9yID0gKGlucHV0LCBzaXplKSA9PiB7XG4gIGNvbnN0IGFyciA9IFtdO1xuICBmb3IgKGxldCBpID0gMDsgaSA8IGlucHV0Lmxlbmd0aDsgaSArPSBzaXplKSB7XG4gICAgYXJyLnB1c2goaW5wdXQuc2xpY2UoaSwgaSArIHNpemUpKTtcbiAgfVxuICByZXR1cm4gYXJyO1xufTsiLCJ0ZXN0cyI6W3sibmFtZSI6Im5hdGl2ZSBuZXciLCJjb2RlIjoiY29uc29sZS5sb2coY2h1bmtOZXcodmFsdWVzLCA0KSkiLCJydW5zIjpbODEyLDg3Miw4NzksOTA5LDg3Miw5MDksODc5LDkwMiw5MDksOTI0LDkxNyw4NzIsOTE3LDk3Nyw5MTcsOTAyLDkwMiw4MjcsODc5LDgxMiw3NjYsODcyLDkzMiw4MTksODEyLDc3NCw5MzksODg3LDk2OSw5MDIsOTU0LDkyNCw5NDcsOTY5LDk1NCw5NDcsODI3LDg4Nyw5MjQsNzQ0LDkyNCw4OTQsOTE3LDkzOSw5ODQsOTMyLDg0OSw4NzksNzk2LDg1Nyw5MjQsODQyLDk3Nyw4NzksOTI0LDg5NCw5NjIsOTAyLDkwMiw4NzksODQyLDgwNCw5NTQsOTE3LDgyNyw5NTQsOTU0LDkxNyw4NzksODE5LDg0OSw3ODksOTU0LDg0Miw5MTcsODc5LDkwOSw4NzksODU3LDkzOSw4NzIsOTQ3LDEwMDcsOTA5LDk2Miw5NzcsOTI0LDk4NCw5MjQsOTAyLDkzOSw4NzksODE5LDcyMSw5NjIsODk0LDk2Miw5NjIsNzc0LDgzNF0sIm9wcyI6ODk0fSx7Im5hbWUiOiJuYXRpdmUgb2xkIiwiY29kZSI6ImNvbnNvbGUubG9nKGNodW5rT2xkKHZhbHVlcywgNCkpIiwicnVucyI6WzgyNyw4NzksODY0LDgwNCw4ODcsOTA5LDkzMiw4NDksODcyLDkzOSw4OTQsOTQ3LDkwOSw5MTcsODk0LDkxNyw3ODEsODY0LDkyNCw4NjQsODE5LDg5NCw5MjQsODcyLDgwNCw4NzIsODEyLDkwOSw5ODQsOTM5LDgzNCwxMDAwLDk3Nyw5NDcsOTYyLDkzOSw4NjQsOTg0LDg2NCw5MDksOTAyLDg4Nyw5MDIsOTYyLDk3Nyw5MTcsOTU0LDg3OSw3ODksOTAyLDk2OSw4MTIsOTE3LDkxNyw5MDIsOTI0LDkzOSw4OTQsODk0LDgzNCw4NzksODQyLDkzOSw4OTQsODI3LDk2Miw4OTQsODc5LDg3Miw3MzYsOTY5LDcxNCw4OTQsODk0LDkxNyw5ODQsOTkyLDg2NCw5MTcsODg3LDk2OSw4NzIsOTQ3LDk4NCw5NzcsOTYyLDg5NCw5NjIsNzc0LDk2OSw5NzcsOTMyLDg1Nyw4NzksOTI0LDkyNCw4NTcsOTM5LDc4MSw5NjJdLCJvcHMiOjg5OX0seyJuYW1lIjoibmF0aXZlIGZvciBsb29wIiwiY29kZSI6IlxuXG5jb25zb2xlLmxvZyhjaHVua0Zvcih2YWx1ZXMsIDQpKSIsInJ1bnMiOlsxMjAsMTM1LDE1NywxNjUsMTUwLDE2NSwxNTcsMTU3LDE2NSwxNTcsMTY1LDE2NSwxNTcsMTU3LDE1NywxNTcsMTM1LDE1NywxNTcsMTU3LDE1NywxNjUsMTU3LDE1NywxNjUsMTQyLDE1NywxNTcsMTU3LDE1MCwxNTcsMTU3LDE2NSwxNTcsMTY1LDE1NywxNTAsMTY1LDE1NywxMzUsMTY1LDE1NywxNTcsMTY1LDE1NywxNTcsMTUwLDE1NywxNjUsMTY1LDE2NSwxNTcsMTU3LDE2NSwxNTcsMTU3LDE2NSwxNTcsMTU3LDE1NywxNTcsMTM1LDE1NywxNTcsMTU3LDE1NywxNTcsMTU3LDE1NywxNjUsMTU3LDE1NywxNTcsMTU3LDE2NSwxNjUsMTU3LDE1NywxNTAsMTU3LDE1NywxNjUsMTY1LDE1NywxNTcsMTU3LDE1MCwxNjUsMTU3LDE1NywxNTcsMTU3LDE1NywxNTcsMTY1LDE1NywxNTcsMTU3LDE1NywxNTddLCJvcHMiOjE1N31dLCJ1cGRhdGVkIjoiMjAyMy0wNi0yNVQxMDoyNzo1Mi4wODNaIn0%3D) I found - surprisingly same weird results :|

**Comment by kungfooman** [comment]
Yup, same results for me, `for + slice` is always faster than `reduce`:

image

Maybe those benchmark pages are functional programming sect leaders and fit the test results for everything containing calls to FP methods... *conspiracy* 🕵️

**Comment by kungfooman** [comment]
Wrong alarm about the sect leaders, you actually have to fill your arrays m8:

image

**Comment by HugeLetters** [comment]
> Wrong alarm about the sect leaders, you actually have to fill your arrays m8:
> 
> image

They are filled. This line.
```
  const testArray = new Array(10000).fill(1).map(Math.random)
```

**Comment by kungfooman** [comment]
[perf.link](https://perf.link/#eyJpZCI6InFkcGJ2bWx4Z2xsIiwidGl0bGUiOiJGaW5kaW5nIG51bWJlcnMgaW4gYW4gYXJyYXkgb2YgMTAwMCIsImJlZm9yZSI6ImNvbnN0IHZhbHVlcyA9IG5ldyBBcnJheSgyMDAgKiAyMDAgKiA0KS5maWxsKDEyMylcbmNvbnN0IGNodW5rTmV3ID0gKGlucHV0LCBzaXplKSA9PiB7XG4gIHJldHVybiBpbnB1dC5yZWR1Y2UoKGFyciwgaXRlbSwgaWR4KSA9PiB7XG4gICAgaWYgKGlkeCAlIHNpemUgPT09IDApIHtcbiAgICAgIGFyci5wdXNoKFtpdGVtXSk7XG4gICAgfVxuICAgIGVsc2Uge1xuICAgICAgYXJyW2Fyci5sZW5ndGggLSAxXS5wdXNoKGl0ZW0pO1xuICAgIH1cblxuICAgIHJldHVybiBhcnI7XG4gIH0sIFtdKTtcbn1cblxuY29uc3QgY2h1bmtPbGQgPSAoaW5wdXQsIHNpemUpID0%2BIHtcbiAgcmV0dXJuIGlucHV0LnJlZHVjZSgoYXJyLCBpdGVtLCBpZHgpID0%2BIHtcbiAgICByZXR1cm4gaWR4ICUgc2l6ZSA9PT0gMFxuICAgICAgPyBbLi4uYXJyLCBbaXRlbV1dXG4gICAgOiBbLi4uYXJyLnNsaWNlKDAsIC0xKSwgWy4uLmFyci5zbGljZSgtMSlbMF0sIGl0ZW1dXTtcbiAgfSwgW10pO1xufVxuXG5jb25zdCBjaHVua0ZvciA9IChpbnB1dCwgc2l6ZSkgPT4ge1xuICBjb25zdCBhcnIgPSBbXTtcbiAgZm9yIChsZXQgaSA9IDA7IGkgPCBpbnB1dC5sZW5ndGg7IGkgKz0gc2l6ZSkge1xuICAgIGFyci5wdXNoKGlucHV0LnNsaWNlKGksIGkgKyBzaXplKSk7XG4gIH1cbiAgcmV0dXJuIGFycjtcbn07IiwidGVzdHMiOlt7Im5hbWUiOiJuYXRpdmUgbmV3IiwiY29kZSI6ImNvbnNvbGUubG9nKGNodW5rTmV3KHZhbHVlcywgNCkpIiwicnVucyI6WzE0OSwxNDksMTQ5LDE0OSwxNDksMTM0LDE0OSwxMzQsMTQ5LDExOSwxNDksMTQ5LDE0OSwxNDksMTQ5LDE0OSwxNDksMTQ5LDE0OSwxNDksMTQ5LDE0OSwxNDksMTQ5LDExOSwxNDksMTQ5LDE0OSwxMzQsMTQ5LDE0OSwxNDksMTQ5LDE0OSwxNDksMTQ5LDE0OSwxNDksMTQ5LDE0OSwxNDksMTQ5LDE0OSwxNDksMTM0LDE0OSwxNDksMTQ5LDEzNCwxMTksMTQ5LDE0OSwxNDksMTQ5LDE0OSwxNDksMTM0LDExOSwxNDksMTM0LDExOSwxNDksMTM0LDE0OSwxNDksMTM0LDE0OSwxNDksMTQ5LDE0OSwxNDksMTQ5LDE0OSwxNDksMTQ5LDE0OSwxNDksMTQ5LDE0OSwxMTksMTQ5LDE0OSwxNDksMTQ5LDE0OSwxMzQsMTQ5LDE0OSwxNDksMTQ5LDE0OSwxNDksMTQ5LDE0OSwxNDksMTM0LDExOSwxNDksMTQ5LDE0OV0sIm9wcyI6MTQ1fSx7Im5hbWUiOiJuYXRpdmUgZm9yIGxvb3AiLCJjb2RlIjoiXG5cbmNvbnNvbGUubG9nKGNodW5rRm9yKHZhbHVlcywgNCkpIiwicnVucyI6WzI2OCwyNjgsMjgzLDI2OCwyNjgsMjY4LDI2OCwyNjgsMjY4LDE5NCwyNjgsMjgzLDI2OCwyNjgsMjY4LDI2OCwyNjgsMjY4LDI2OCwyNTMsMjY4LDI2OCwyNjgsMjUzLDI1MywyNjgsMjY4LDI2OCwyNjgsMjgzLDI4MywyNjgsMjk4LDI2OCwyNjgsMjY4LDI2OCwyNTMsMjY4LDI4MywyODMsMjk4LDI2OCwyNjgsMjUzLDI2OCwzMTMsMjgzLDI5OCwyMzgsMjUzLDI1MywyNTMsMjY4LDI5OCwyODMsMjUzLDI1MywyNjgsMjUzLDI1MywyNTMsMjgzLDI5OCwyNjgsMjk4LDI2OCwyNjgsMjY4LDI1MywyNjgsMjUzLDI4MywyNjgsMjY4LDI2OCwyNjgsMjY4LDI2OCwyNTMsMjY4LDI5OCwyODMsMjk4LDI2OCwyNjgsMjUzLDI2OCwyNjgsMjY4LDI2OCwyNjgsMjY4LDI1MywyNjgsMjY4LDI1MywyNjgsMjY4LDI2OF0sIm9wcyI6MjY4fV0sInVwZGF0ZWQiOiIyMDIzLTA2LTI1VDExOjIwOjEwLjc1MVoifQ%3D%3D)

I mean here... I removed the old version, because it can't even handle the load (tab crashes).

New result:

image

(2) being for/splice-version

**Comment by kungfooman** [comment]
> They are filled. This line.

Yep, I realized it started unfilled with @ODudek first benchmark test

**Comment by HugeLetters** [comment]
> [perf.link](https://perf.link/#eyJpZCI6InFkcGJ2bWx4Z2xsIiwidGl0bGUiOiJGaW5kaW5nIG51bWJlcnMgaW4gYW4gYXJyYXkgb2YgMTAwMCIsImJlZm9yZSI6ImNvbnN0IHZhbHVlcyA9IG5ldyBBcnJheSgyMDAgKiAyMDAgKiA0KS5maWxsKDEyMylcbmNvbnN0IGNodW5rTmV3ID0gKGlucHV0LCBzaXplKSA9PiB7XG4gIHJldHVybiBpbnB1dC5yZWR1Y2UoKGFyciwgaXRlbSwgaWR4KSA9PiB7XG4gICAgaWYgKGlkeCAlIHNpemUgPT09IDApIHtcbiAgICAgIGFyci5wdXNoKFtpdGVtXSk7XG4gICAgfVxuICAgIGVsc2Uge1xuICAgICAgYXJyW2Fyci5sZW5ndGggLSAxXS5wdXNoKGl0ZW0pO1xuICAgIH1cblxuICAgIHJldHVybiBhcnI7XG4gIH0sIFtdKTtcbn1cblxuY29uc3QgY2h1bmtPbGQgPSAoaW5wdXQsIHNpemUpID0%2BIHtcbiAgcmV0dXJuIGlucHV0LnJlZHVjZSgoYXJyLCBpdGVtLCBpZHgpID0%2BIHtcbiAgICByZXR1cm4gaWR4ICUgc2l6ZSA9PT0gMFxuICAgICAgPyBbLi4uYXJyLCBbaXRlbV1dXG4gICAgOiBbLi4uYXJyLnNsaWNlKDAsIC0xKSwgWy4uLmFyci5zbGljZSgtMSlbMF0sIGl0ZW1dXTtcbiAgfSwgW10pO1xufVxuXG5jb25zdCBjaHVua0ZvciA9IChpbnB1dCwgc2l6ZSkgPT4ge1xuICBjb25zdCBhcnIgPSBbXTtcbiAgZm9yIChsZXQgaSA9IDA7IGkgPCBpbnB1dC5sZW5ndGg7IGkgKz0gc2l6ZSkge1xuICAgIGFyci5wdXNoKGlucHV0LnNsaWNlKGksIGkgKyBzaXplKSk7XG4gIH1cbiAgcmV0dXJuIGFycjtcbn07IiwidGVzdHMiOlt7Im5hbWUiOiJuYXRpdmUgbmV3IiwiY29kZSI6ImNvbnNvbGUubG9nKGNodW5rTmV3KHZhbHVlcywgNCkpIiwicnVucyI6WzE0OSwxNDksMTQ5LDE0OSwxNDksMTM0LDE0OSwxMzQsMTQ5LDExOSwxNDksMTQ5LDE0OSwxNDksMTQ5LDE0OSwxNDksMTQ5LDE0OSwxNDksMTQ5LDE0OSwxNDksMTQ5LDExOSwxNDksMTQ5LDE0OSwxMzQsMTQ5LDE0OSwxNDksMTQ5LDE0OSwxNDksMTQ5LDE0OSwxNDksMTQ5LDE0OSwxNDksMTQ5LDE0OSwxNDksMTM0LDE0OSwxNDksMTQ5LDEzNCwxMTksMTQ5LDE0OSwxNDksMTQ5LDE0OSwxNDksMTM0LDExOSwxNDksMTM0LDExOSwxNDksMTM0LDE0OSwxNDksMTM0LDE0OSwxNDksMTQ5LDE0OSwxNDksMTQ5LDE0OSwxNDksMTQ5LDE0OSwxNDksMTQ5LDE0OSwxMTksMTQ5LDE0OSwxNDksMTQ5LDE0OSwxMzQsMTQ5LDE0OSwxNDksMTQ5LDE0OSwxNDksMTQ5LDE0OSwxNDksMTM0LDExOSwxNDksMTQ5LDE0OV0sIm9wcyI6MTQ1fSx7Im5hbWUiOiJuYXRpdmUgZm9yIGxvb3AiLCJjb2RlIjoiXG5cbmNvbnNvbGUubG9nKGNodW5rRm9yKHZhbHVlcywgNCkpIiwicnVucyI6WzI2OCwyNjgsMjgzLDI2OCwyNjgsMjY4LDI2OCwyNjgsMjY4LDE5NCwyNjgsMjgzLDI2OCwyNjgsMjY4LDI2OCwyNjgsMjY4LDI2OCwyNTMsMjY4LDI2OCwyNjgsMjUzLDI1MywyNjgsMjY4LDI2OCwyNjgsMjgzLDI4MywyNjgsMjk4LDI2OCwyNjgsMjY4LDI2OCwyNTMsMjY4LDI4MywyODMsMjk4LDI2OCwyNjgsMjUzLDI2OCwzMTMsMjgzLDI5OCwyMzgsMjUzLDI1MywyNTMsMjY4LDI5OCwyODMsMjUzLDI1MywyNjgsMjUzLDI1MywyNTMsMjgzLDI5OCwyNjgsMjk4LDI2OCwyNjgsMjY4LDI1MywyNjgsMjUzLDI4MywyNjgsMjY4LDI2OCwyNjgsMjY4LDI2OCwyNTMsMjY4LDI5OCwyODMsMjk4LDI2OCwyNjgsMjUzLDI2OCwyNjgsMjY4LDI2OCwyNjgsMjY4LDI1MywyNjgsMjY4LDI1MywyNjgsMjY4LDI2OF0sIm9wcyI6MjY4fV0sInVwZGF0ZWQiOiIyMDIzLTA2LTI1VDExOjIwOjEwLjc1MVoifQ%3D%3D)
> 
> I mean here... I removed the old version, because it can't even handle the load (tab crashes).
> 
> New result:
> 
> image
> 
> (2) being for/splice-version

Oh right, I think that explains the first benchmark too - I've just copied it over to a new site without looking too much into it

**Comment by kungfooman** [comment]
@HugeLetters So what's you plan, make a PR with fastest version?

**Comment by HugeLetters** [comment]
> @HugeLetters So what's you plan, make a PR with fastest version?

Nah, I've closed it since there's no response from people on the contributors team - if they have no interest in improving the examples then so be it.

**Comment by kungfooman** [comment]
@HugeLetters Right, so @ODudek, would you have time to review and merge, once @HugeLetters would change to fastest version?

**Pull request closed without merging**
